### ISSUE TITLE
slow style not working

### ISSUE THREAD

**Issue by frolf** [ghwatson/faststyle#1]
Unable to run slow_style.py. Other aspects functioning properly, but receiving the following error. Environment consists of machine running Ubuntu 16.04 :

-python 2.7.13
-tensorflow-gpu 1.0.0
-opencv 3.1.0
-numpy 1.11.3

---------------
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /root/mc-x64-2.7/conda-bld/opencv-3_1482256854890/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7341
Traceback (most recent call last):
  File "slow_style.py", line 189, in <module>
    main(args)
  File "slow_style.py", line 86, in main
    style_img = utils.imread(style_img_path)
  File "/home/shannon/Desktop/faststyle/utils.py", line 21, in imread
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: /root/mc-x64-2.7/conda-bld/opencv-3_1482256854890/work/opencv-3.1.0/modules/imgproc/src/color.cpp:7341: error: (-215) scn == 3 || scn == 4 in function ipp_cvtColor

-------------

Any suggestions?

**Comment by ghwatson** [comment]
I believe the issue is just a typo in my documentation where I show example usage. I forgot ".jpg" on the end of the style image name. See b963c5ed307be0ebdb38465bf992f9820cfcb1dd to see what I mean and let me know if that was the cause of your error.

**Comment by frolf** [comment]
It was, thanks for the help and appreciate sharing your implementation.
